from __future__ import annotations

import argparse
import importlib.util
import json
import os
import shutil
import socket
import subprocess
import sys
import threading
import time
import urllib.request
import webbrowser
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _port_available(host: str, port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.25)
        return sock.connect_ex((host, int(port))) != 0


def _first_available_port(host: str, start_port: int, attempts: int) -> int:
    for offset in range(max(1, attempts)):
        port = int(start_port) + offset
        if _port_available(host, port):
            return port
    raise RuntimeError(f"No free local port found from {start_port} through {start_port + attempts - 1}.")


def _validate_local_python() -> None:
    if sys.version_info[:2] != (3, 11):
        raise SystemExit(
            "EDIM local runtime must be started with Python 3.11 because the packaged Calliope runtime "
            "depends on calliope==0.6.10 and numpy==1.23.5. Recreate/activate the environment with:\n"
            "  python3.11 -m venv backend/.venv\n"
            "  source backend/.venv/bin/activate\n"
            "  pip3 install -r backend/requirements.txt\n"
            "  pip3 install --no-build-isolation -e ./model_runtime"
        )
    if importlib.util.find_spec("calliope") is None:
        raise SystemExit(
            "The active Python 3.11 environment does not have the model runtime installed. Run:\n"
            "  source backend/.venv/bin/activate\n"
            "  pip3 install -r backend/requirements.txt\n"
            "  pip3 install --no-build-isolation -e ./model_runtime"
        )


def _write_frontend_runtime_config(frontend_dir: Path) -> None:
    backend_base = (_env_value("EDIM_BACKEND_API_BASE", _repo_root()) or "").strip().rstrip("/")
    target = frontend_dir / "runtime-config.local.js"
    target.write_text(
        "\n".join(
            [
                "// Generated by scripts/run_local.py from the local environment.",
                "// The local UI and API are served together, including when the launcher selects a fallback port.",
                "window.EDIM_LOCAL_API_BASE = window.location.origin;",
                f"window.EDIM_BACKEND_API_BASE = {json.dumps(backend_base)};",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _env_value(key: str, repo_root: Path) -> str:
    value = os.getenv(key)
    if value is not None:
        return value
    env_path = repo_root / ".env"
    if not env_path.exists():
        return ""
    for line in env_path.read_text(encoding="utf-8").splitlines():
        text = line.strip()
        if not text or text.startswith("#") or "=" not in text:
            continue
        name, raw = text.split("=", 1)
        if name.strip() != key:
            continue
        cleaned = raw.strip()
        if (cleaned.startswith('"') and cleaned.endswith('"')) or (cleaned.startswith("'") and cleaned.endswith("'")):
            cleaned = cleaned[1:-1]
        return cleaned
    return ""


def _build_frontend_bundle(frontend_source_dir: Path) -> Path:
    dist_dir = frontend_source_dir / "dist"
    build_script = frontend_source_dir / "scripts" / "build-static.js"
    if not build_script.exists():
        raise SystemExit("Frontend build script not found at frontend/scripts/build-static.js.")
    node_cmd = shutil.which("node")
    if node_cmd is None:
        for candidate in (
            "/opt/homebrew/opt/node@22/bin/node",
            "/opt/homebrew/bin/node",
            "/usr/local/bin/node",
        ):
            if Path(candidate).exists():
                node_cmd = candidate
                break
    if node_cmd is None:
        raise SystemExit(
            "Node.js is required to build the local frontend bundle before serving /ui/. "
            "Install Node.js or add it to PATH."
        )
    try:
        subprocess.run([node_cmd, str(build_script)], cwd=str(frontend_source_dir), check=True)
    except FileNotFoundError as exc:
        raise SystemExit("Node.js is required to build the local frontend bundle before serving /ui/.") from exc
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"Frontend static bundle build failed with exit code {exc.returncode}.") from exc
    if not (dist_dir / "index.html").exists():
        raise SystemExit("Frontend build did not produce frontend/dist/index.html.")
    return dist_dir


def _env_flag(key: str, default: bool) -> bool:
    value = os.getenv(key)
    if value is None:
        return default
    return value.strip().lower() not in {"0", "false", "no", "off"}


def _open_browser_when_ready(url: str, enabled: bool) -> None:
    if not enabled:
        return

    def worker() -> None:
        deadline = time.time() + 30
        while time.time() < deadline:
            try:
                with urllib.request.urlopen(url, timeout=0.5):
                    break
            except Exception:
                time.sleep(0.25)
        try:
            webbrowser.open(url)
        except Exception as exc:
            print(f"Could not open browser automatically: {exc}", flush=True)

    thread = threading.Thread(target=worker, name="edim-browser-opener", daemon=True)
    thread.start()


def _write_local_app_state(repo_root: Path, url: str) -> tuple[Path, Path]:
    state_dir = repo_root / "outputs"
    state_dir.mkdir(parents=True, exist_ok=True)
    pid_file = state_dir / "local_app.pid"
    url_file = state_dir / "local_app.url"
    pid_file.write_text(f"{os.getpid()}\n", encoding="utf-8")
    url_file.write_text(f"{url}\n", encoding="utf-8")
    return pid_file, url_file


def _clear_local_app_state(pid_file: Path, url_file: Path) -> None:
    try:
        if pid_file.exists() and pid_file.read_text(encoding="utf-8").strip() == str(os.getpid()):
            pid_file.unlink()
            if url_file.exists():
                url_file.unlink()
    except OSError:
        pass


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the EDIM local backend handoff surface.")
    parser.add_argument("--host", default=os.getenv("EDIM_HOST", "127.0.0.1"))
    parser.add_argument("--port", type=int, default=int(os.getenv("EDIM_PORT", "8000")))
    parser.add_argument("--port-attempts", type=int, default=int(os.getenv("EDIM_PORT_ATTEMPTS", "50")))
    parser.add_argument("--open", dest="open_browser", action="store_true", help="Open the UI in the default browser after startup.")
    parser.add_argument("--no-open", dest="open_browser", action="store_false", help="Do not open a browser automatically.")
    parser.set_defaults(open_browser=_env_flag("EDIM_OPEN_BROWSER", True))
    args = parser.parse_args()
    _validate_local_python()

    repo_root = _repo_root()
    backend_dir = repo_root / "backend"
    frontend_source_dir = repo_root / "frontend"
    runtime_config = repo_root / "inputs" / "runtime_config.json"
    if not (backend_dir / "api_service" / "main.py").exists():
        raise SystemExit("Backend entrypoint not found.")
    if not (frontend_source_dir / "index.html").exists():
        raise SystemExit("Frontend index.html not found.")
    if not runtime_config.exists():
        raise SystemExit("inputs/runtime_config.json not found.")
    frontend_dir = _build_frontend_bundle(frontend_source_dir)
    port = _first_available_port(str(args.host), int(args.port), int(args.port_attempts))
    if port != int(args.port):
        print(f"Port {args.port} is busy; using {port}.", flush=True)
    _write_frontend_runtime_config(frontend_dir)

    env = os.environ.copy()
    python_path_parts = [str(repo_root), str(repo_root / "model_runtime")]
    if env.get("PYTHONPATH"):
        python_path_parts.append(env["PYTHONPATH"])
    env["PYTHONPATH"] = os.pathsep.join(python_path_parts)
    env.setdefault("EDIM_FRONTEND_DIR", str(frontend_dir))
    env.setdefault("EDIM_RUNTIME_CONFIG", str(runtime_config))

    ui_url = f"http://{args.host}:{port}/ui/"
    print("EDIM local app", flush=True)
    print(f"UI:      {ui_url}", flush=True)
    print(f"API:     http://{args.host}:{port}/api/system/manifest", flush=True)
    backend_target = (_env_value("EDIM_BACKEND_API_BASE", repo_root) or "").strip().rstrip("/")
    if backend_target:
        print(f"Backend target: {backend_target}", flush=True)
    print("Runtime: project-owned run flow with subprocess model handoff", flush=True)
    if args.open_browser:
        print("Browser: opening automatically when the UI is ready", flush=True)

    cmd = [
        sys.executable,
        "-m",
        "uvicorn",
        "api_service.main:app",
        "--app-dir",
        str(backend_dir),
        "--host",
        str(args.host),
        "--port",
        str(port),
    ]
    pid_file, url_file = _write_local_app_state(repo_root, ui_url)
    _open_browser_when_ready(ui_url, bool(args.open_browser))
    try:
        return subprocess.call(cmd, cwd=str(repo_root), env=env)
    finally:
        _clear_local_app_state(pid_file, url_file)


if __name__ == "__main__":
    raise SystemExit(main())
